export default [
    {
        "isDir": true,
        "id": "b1d9dfe9-a69c-476a-b350-333eba67e65c",
        "pageCount": 0,
        "filePath": "\\storage\\newone\\newone",
        "folderId": "0c8fea63-1741-412f-8ae9-9c10bc79ea91",
        "name": "big.pdf",
        "slug": "big.pdf",
        "parentId": "0c8fea63-1741-412f-8ae9-9c10bc79ea91",
        "sftpId": null,
        "ext": "pdf",
        "size": "60926",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-11T05:54:52.911Z",
        "updatedAt": "2025-02-11T13:38:33.071Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-11T13:38:33.071Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "60b8f62f-9933-4f35-a2fd-decacce25737",
        "name": "vijay nodejs",
        "slug": "vijay-nodejs",
        "parentId": "0c8fea63-1741-412f-8ae9-9c10bc79ea91",
        "folderPath": "vijay nodejs",
        "sftpId": null,
        "ext": null,
        "size": "60926",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-11T05:54:52.911Z",
        "updatedAt": "2025-02-11T13:38:33.071Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-11T13:38:33.071Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "f0149988-1af5-4a96-9ebf-ca788c41278f",
        "name": "vijay nodejs",
        "slug": "vijay-nodejs",
        "parentId": null,
        "folderPath": "vijay nodejs",
        "sftpId": null,
        "ext": null,
        "size": "60926",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-11T05:54:52.911Z",
        "updatedAt": "2025-02-11T13:38:33.071Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-11T13:38:33.071Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "cfc50436-e988-4ddd-b251-d7a0a6222c19",
        "name": "Roots Group",
        "slug": "roots-group",
        "parentId": null,
        "folderPath": "Roots Group",
        "sftpId": null,
        "ext": null,
        "size": "8944175",
        "maxSize": "5368709120",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-18T02:57:59.026Z",
        "updatedAt": "2025-02-21T05:22:52.017Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 8,
        "modDate": "2025-02-21T05:22:52.017Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "678f1979-b5ae-48dc-868c-79c7436e90be",
        "name": "test cab 3",
        "slug": "test-cab-3",
        "parentId": null,
        "folderPath": "test cab 3",
        "sftpId": null,
        "ext": null,
        "size": "2580824",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-13T08:54:56.524Z",
        "updatedAt": "2025-02-13T09:49:33.202Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-13T09:49:33.202Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "477217d1-fc5d-4a7f-bb74-24a53e150259",
        "name": "PV",
        "slug": "pv",
        "parentId": null,
        "folderPath": "PV",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-11T06:02:42.400Z",
        "updatedAt": "2025-02-11T06:02:42.400Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 0,
        "modDate": "2025-02-11T06:02:42.400Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "d4ae54ea-5a0b-4bb3-a12a-e13a30959e90",
        "name": "santhosh",
        "slug": "santhosh",
        "parentId": null,
        "folderPath": "santhosh",
        "sftpId": null,
        "ext": null,
        "size": "194089",
        "maxSize": "1073741824",
        "description": "new to work",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-13T12:22:07.907Z",
        "updatedAt": "2025-02-20T04:09:26.384Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-20T04:09:26.384Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "0aa1a9c0-1932-4a40-a136-a2f4475d3aeb",
        "name": "Test Cab 2",
        "slug": "test-cab-2",
        "parentId": null,
        "folderPath": "Test Cab 2",
        "sftpId": null,
        "ext": null,
        "size": "35706236",
        "maxSize": "2147483648",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-01T06:02:50.528Z",
        "updatedAt": "2025-02-24T09:12:50.673Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 3,
        "modDate": "2025-02-24T09:12:50.673Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "ab28d892-a9ee-4b45-b90f-85aca8e01fe1",
        "name": "test vijay",
        "slug": "test-vijay",
        "parentId": null,
        "folderPath": "test vijay",
        "sftpId": null,
        "ext": null,
        "size": "25314",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-05T07:11:58.295Z",
        "updatedAt": "2025-02-12T04:29:52.484Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 2,
        "modDate": "2025-02-12T04:29:52.484Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "4c453089-f63a-42bb-bc93-fb2003c1baaa",
        "name": "Audit log checking cabinet",
        "slug": "audit-log-checking-cabinet",
        "parentId": null,
        "folderPath": "Audit log checking cabinet",
        "sftpId": null,
        "ext": null,
        "size": "10545071",
        "maxSize": "2147483648",
        "description": "cabinet creation test",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-12T09:47:01.396Z",
        "updatedAt": "2025-02-15T10:06:45.208Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 4,
        "modDate": "2025-02-15T10:06:45.208Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "335f0f77-e413-4d6a-b729-d60df401d257",
        "name": "new cabinet",
        "slug": "new-cabinet",
        "parentId": null,
        "folderPath": "new cabinet",
        "sftpId": null,
        "ext": null,
        "size": "118820",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-04T05:12:44.762Z",
        "updatedAt": "2025-02-11T05:44:22.477Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 2,
        "modDate": "2025-02-11T05:44:22.477Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "3db5d3da-9bfe-4557-97cd-e64e84e62384",
        "name": "Procurement",
        "slug": "procurement",
        "parentId": null,
        "folderPath": "Procurement",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "10485760",
        "description": "Procurement Cabinet",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-21T07:33:13.536Z",
        "updatedAt": "2025-02-21T07:33:13.536Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-21T07:33:13.536Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "97fb8eb1-de9e-4f14-98ce-b9a41f01ed1b",
        "name": "Bulk Upload Testing",
        "slug": "bulk-upload-testing",
        "parentId": null,
        "folderPath": "Bulk Upload Testing",
        "sftpId": null,
        "ext": null,
        "size": "53350882",
        "maxSize": "2147483648",
        "description": "Bulk Upload With Meta",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-04T05:34:49.900Z",
        "updatedAt": "2025-02-12T09:55:43.384Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-12T09:55:43.384Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "4d743a0c-b8a3-4fb3-8e9e-7dae8b5118aa",
        "name": "Bulk Upload With Metadata",
        "slug": "bulk-upload-with-metadata",
        "parentId": null,
        "folderPath": "Bulk Upload With Metadata",
        "sftpId": null,
        "ext": null,
        "size": "52834884",
        "maxSize": "2147483648",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-04T05:35:53.441Z",
        "updatedAt": "2025-02-06T10:05:54.276Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-06T10:05:54.276Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "0d07ebfe-8417-4db8-b75f-1c403340b21d",
        "name": "DD",
        "slug": "dd",
        "parentId": null,
        "folderPath": "DD",
        "sftpId": null,
        "ext": null,
        "size": "32631697",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-12T20:53:04.284Z",
        "updatedAt": "2025-02-13T07:23:55.618Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 2,
        "modDate": "2025-02-13T07:23:55.618Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "9d2baf06-ed84-45e1-9112-cd23d9bbda20",
        "name": "AD",
        "slug": "ad",
        "parentId": null,
        "folderPath": "AD",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-12T21:02:53.371Z",
        "updatedAt": "2025-02-12T21:02:53.371Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 0,
        "modDate": "2025-02-12T21:02:53.371Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "4718f75f-50c4-442c-bcdb-cd9e5db1a23a",
        "name": "Requirement",
        "slug": "requirement",
        "parentId": null,
        "folderPath": "Requirement",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "10485760",
        "description": "Cabinet",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-21T08:52:45.655Z",
        "updatedAt": "2025-02-21T08:52:45.655Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-21T08:52:45.655Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "bf5c04a2-eeb6-43fe-9bc5-7cc8f42d0a1f",
        "name": "RR",
        "slug": "rr",
        "parentId": null,
        "folderPath": "RR",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-12T21:17:13.386Z",
        "updatedAt": "2025-02-12T21:17:13.386Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-12T21:17:13.386Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "2451e945-765a-4af0-a55f-6105a99e81c8",
        "name": "test1002",
        "slug": "test1002",
        "parentId": null,
        "folderPath": "test1002",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "5242880",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-02-10T14:32:09.261Z",
        "updatedAt": "2025-02-10T14:32:09.261Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 0,
        "modDate": "2025-02-10T14:32:09.261Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "8570a63e-c632-489a-8933-7541efbdb023",
        "name": "vk",
        "slug": "vk",
        "parentId": null,
        "folderPath": "vk",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "1048576",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": null,
        "updatedBy": null,
        "createdAt": "2024-12-09T12:01:17.172Z",
        "updatedAt": "2025-02-11T07:37:35.887Z",
        "deletedAt": null,
        "updatedUser": null,
        "createdUser": null,
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-11T07:37:35.887Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "c088bb5d-cd38-46c1-8530-1f81bb805c53",
        "name": "J Pradeepan",
        "slug": "j-pradeepan",
        "parentId": null,
        "folderPath": "J Pradeepan",
        "sftpId": null,
        "ext": null,
        "size": "20885905",
        "maxSize": "20971520",
        "description": "description",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-10-28T10:25:24.736Z",
        "updatedAt": "2025-02-07T07:19:27.980Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 10,
        "modDate": "2025-02-07T07:19:27.980Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "a74a1210-87a0-4421-9f04-b49364968317",
        "name": "OCR Test",
        "slug": "ocr-test",
        "parentId": null,
        "folderPath": "OCR Test",
        "sftpId": null,
        "ext": null,
        "size": "3492082421",
        "maxSize": "5368709120",
        "description": "Single and bulk upload OCR test",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-12-23T04:47:57.780Z",
        "updatedAt": "2025-02-10T10:47:13.860Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 19,
        "modDate": "2025-02-10T10:47:13.860Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "d64ae060-d667-4086-af65-8167a5d9761b",
        "name": "Workflow test",
        "slug": "workflow-test",
        "parentId": null,
        "folderPath": "Workflow test",
        "sftpId": null,
        "ext": null,
        "size": "327033999",
        "maxSize": "5368709120",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-01-08T10:17:04.892Z",
        "updatedAt": "2025-02-24T09:44:29.300Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 3,
        "modDate": "2025-02-24T09:44:29.300Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "659048d3-4340-4bc1-b641-0949330d981e",
        "name": "ocr-files",
        "slug": "ocr-files",
        "parentId": null,
        "folderPath": "ocr-files",
        "sftpId": null,
        "ext": null,
        "size": "27038493",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-01-02T13:10:03.940Z",
        "updatedAt": "2025-01-08T07:14:59.143Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 6,
        "modDate": "2025-01-08T07:14:59.143Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "b578fa70-4a0e-4842-978a-6fb7c80c95a3",
        "name": "Kirubha",
        "slug": "kirubha",
        "parentId": null,
        "folderPath": "Kirubha",
        "sftpId": null,
        "ext": null,
        "size": "15148057",
        "maxSize": "524288000",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-01-28T14:02:37.268Z",
        "updatedAt": "2025-02-20T10:22:44.580Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-20T10:22:44.580Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "82df8054-099b-4d4d-a2a3-8f70f97e00ae",
        "name": "newone",
        "slug": "newone",
        "parentId": null,
        "folderPath": "newone",
        "sftpId": null,
        "ext": null,
        "size": "10058511",
        "maxSize": "7516192768",
        "description": "dwg viewer test",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13e2e195-72df-4bf7-b690-71d22dc1b587",
        "updatedBy": "13e2e195-72df-4bf7-b690-71d22dc1b587",
        "createdAt": "2025-01-06T04:51:56.835Z",
        "updatedAt": "2025-02-09T17:02:10.852Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13e2e195-72df-4bf7-b690-71d22dc1b587",
            "userName": "Elon",
            "firstName": "Elon",
            "lastName": "Musk"
        },
        "createdUser": {
            "id": "13e2e195-72df-4bf7-b690-71d22dc1b587",
            "userName": "Elon",
            "firstName": "Elon",
            "lastName": "Musk"
        },
        "metaFolderStructure": [],
        "childrenCount": 2,
        "modDate": "2025-02-09T17:02:10.852Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "f3b3e48b-e398-460e-b5c3-14a65eff1254",
        "name": "Lav",
        "slug": "lav",
        "parentId": null,
        "folderPath": "Lav",
        "sftpId": null,
        "ext": null,
        "size": "98304",
        "maxSize": "10485760",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "d4815398-46d8-446b-ba16-8e3fb2ac9fcc",
        "updatedBy": "d4815398-46d8-446b-ba16-8e3fb2ac9fcc",
        "createdAt": "2024-11-05T15:03:25.362Z",
        "updatedAt": "2024-11-05T15:19:29.190Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "d4815398-46d8-446b-ba16-8e3fb2ac9fcc",
            "userName": "lavanya@cannymindsuat.com",
            "firstName": "Lavanya",
            "lastName": "S"
        },
        "createdUser": {
            "id": "d4815398-46d8-446b-ba16-8e3fb2ac9fcc",
            "userName": "lavanya@cannymindsuat.com",
            "firstName": "Lavanya",
            "lastName": "S"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2024-11-05T15:19:29.190Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "a1ad93bc-a45c-4fba-a83c-861a29fcb45f",
        "name": "Work FLow",
        "slug": "work-flow",
        "parentId": null,
        "folderPath": "Work FLow",
        "sftpId": null,
        "ext": null,
        "size": "464391",
        "maxSize": "104857600",
        "description": "Work FLow",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-10-30T05:19:22.377Z",
        "updatedAt": "2025-01-08T06:42:36.616Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 2,
        "modDate": "2025-01-08T06:42:36.616Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": false,
        "id": "565b08d4-1071-45f6-ab37-023f045428bc",
        "name": "codee",
        "slug": "codee",
        "parentId": null,
        "folderPath": "codee",
        "sftpId": null,
        "ext": null,
        "size": "0",
        "maxSize": "0",
        "description": null,
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-10-24T05:28:10.518Z",
        "updatedAt": "2024-10-24T05:28:10.518Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 0,
        "modDate": "2024-10-24T05:28:10.518Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "429a7dd6-7532-47bc-8eda-926676507449",
        "name": "UI Design",
        "slug": "ui-design",
        "parentId": null,
        "folderPath": "UI Design",
        "sftpId": null,
        "ext": null,
        "size": "7630473",
        "maxSize": "1073741824",
        "description": "CannyMinds",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-11-11T21:35:25.869Z",
        "updatedAt": "2025-01-25T22:05:35.058Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-01-25T22:05:35.058Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "96ada5d3-ffac-4957-bf94-2c79a86ae828",
        "name": "Software Development Life Cycle[SDLC]-JAN 2025-WORKFLOW",
        "slug": "software-development-life-cyclesdlc-jan-2025-workflow",
        "parentId": null,
        "folderPath": "Software Development Life Cycle[SDLC]-JAN 2025-WORKFLOW",
        "sftpId": null,
        "ext": null,
        "size": "3122528",
        "maxSize": "5368709120",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-01-08T11:49:43.394Z",
        "updatedAt": "2025-02-13T12:22:27.983Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-13T12:22:27.983Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": true,
        "id": "225743d3-b603-40b1-84f0-a7f93bc0e4ee",
        "name": "sample1",
        "slug": "sample1",
        "parentId": null,
        "folderPath": "sample1",
        "sftpId": null,
        "ext": null,
        "size": "7780809",
        "maxSize": "1073741824",
        "description": "",
        "remarks": null,
        "status": 1,
        "folderState": "ready",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-01-27T09:45:40.054Z",
        "updatedAt": "2025-02-21T07:13:53.902Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaFolderStructure": [],
        "childrenCount": 1,
        "modDate": "2025-02-21T07:13:53.902Z",
        "rightDetails": [
            "view",
            "create",
            "delete",
            "upload",
            "version",
            "move",
            "copy",
            "share",
            "folder-subscription",
            "mail",
            "rename",
            "print-with-annotation",
            "print-without-annotation",
            "annotations",
            "signature",
            "download-with-annotation",
            "download-without-Annotation",
            "document-view",
            "document-upload",
            "document-delete",
            "document-move",
            "document-copy",
            "document-share",
            "document-rename",
            "document-download",
            "document-annotations",
            "document-signature"
        ],
        "isMetaData": false
    },
    {
        "isDir": false,
        "id": "c20ab304-c9b9-451f-8694-247567f7211b",
        "originalName": "2223-min.jpg",
        "fileName": "2223-min.jpg",
        "pageCount": 1,
        "filePath": "\\storage\\Work FLow\\Work FLow",
        "slug": null,
        "folderId": "4ed362f5-aa01-4d4c-96d8-e658c17c38f9",
        "metadataId": null,
        "ext": "jpg",
        "size": "401635",
        "versionNumber": "0",
        "keyword": null,
        "note": null,
        "description": null,
        "remarks": null,
        "fileState": "ready",
        "status": 1,
        "lastAccessed": "2024-11-11T13:00:05.504Z",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-11-11T12:59:30.192Z",
        "updatedAt": "2024-12-04T03:44:06.536Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaAttribute": null,
        "modDate": "2024-12-04T03:44:06.536Z",
        "isMetaData": false
    },
    {
        "isDir": false,
        "id": "abc0006c-2dcc-470b-8e98-76e6b3a6bbe8",
        "originalName": "wbs.xlsx",
        "fileName": "wbs.xlsx",
        "pageCount": 1,
        "filePath": "\\storage\\Work FLow\\Work FLow",
        "slug": null,
        "folderId": "4ed362f5-aa01-4d4c-96d8-e658c17c38f9",
        "metadataId": null,
        "ext": "xlsx",
        "size": "5620",
        "versionNumber": "0",
        "keyword": null,
        "note": null,
        "description": null,
        "remarks": null,
        "fileState": "ready",
        "status": 1,
        "lastAccessed": "2024-11-22T08:08:34.132Z",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-11-22T08:08:33.581Z",
        "updatedAt": "2024-11-22T08:08:33.581Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaAttribute": null,
        "modDate": "2024-11-22T08:08:33.581Z",
        "isMetaData": false
    },
    {
        "isDir": false,
        "id": "304991da-d6eb-4411-b43e-d6d34a3761f9",
        "originalName": "sample1.xlsx",
        "fileName": "sample1.xlsx",
        "pageCount": 0,
        "filePath": "\\storage\\Work FLow\\Work FLow",
        "slug": null,
        "folderId": "4ed362f5-aa01-4d4c-96d8-e658c17c38f9",
        "metadataId": null,
        "ext": "xlsx",
        "size": "0",
        "versionNumber": "0",
        "keyword": null,
        "note": null,
        "description": null,
        "remarks": null,
        "fileState": "processing",
        "status": 1,
        "lastAccessed": "2024-12-27T11:07:26.971Z",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2024-12-27T11:07:25.880Z",
        "updatedAt": "2024-12-27T11:07:25.880Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaAttribute": null,
        "modDate": "2024-12-27T11:07:25.880Z",
        "isMetaData": false
    },
    {
        "isDir": false,
        "id": "69abd1ad-f437-4f48-bd47-898c7d7c1483",
        "originalName": "gettyimages-1090720836-594x594.jpg",
        "fileName": "gettyimages-1090720836-594x594.jpg",
        "pageCount": 0,
        "filePath": "\\storage\\Work FLow\\Work FLow",
        "slug": null,
        "folderId": "4ed362f5-aa01-4d4c-96d8-e658c17c38f9",
        "metadataId": null,
        "ext": "jpg",
        "size": "57136",
        "versionNumber": "0",
        "keyword": null,
        "note": null,
        "description": null,
        "remarks": null,
        "fileState": "ready",
        "status": 1,
        "lastAccessed": "2025-01-08T06:42:38.055Z",
        "createdBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "updatedBy": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
        "createdAt": "2025-01-08T06:42:36.540Z",
        "updatedAt": "2025-01-08T06:42:36.596Z",
        "deletedAt": null,
        "updatedUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "createdUser": {
            "id": "13bdc64a-bda4-4ea2-a258-2c3f714832ee",
            "userName": "CannyMinds",
            "firstName": "CannyMinds",
            "lastName": "Technologies"
        },
        "metaAttribute": {
            "id": "694e353e-f240-430b-bc13-58114cccf1a7",
            "metaJson": "{\"Name\":\"Indian Team\",\"Age\":\"12 \"}",
            "metaDataId": "b69992e2-5e9e-4f4d-ba2b-d68e628d2657",
            "metaDataList": {
                "name": "G"
            }
        },
        "modDate": "2025-01-08T06:42:36.596Z",
        "isMetaData": true,
        "metaName": "G"
    }
];